export const estudante = {
  nome: "Eduardo Gomes de Souza",
  email: "eduardo.gomes@gmail.com",
  primeiroAcesso: "12/07/2021",
  ultimoAcesso: "12/07/2021 - 22:43",
  mediaGeral: 30,
  mediaGeralPorcentagem: "30%",
  desafios: [
    {
      descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elite.",
      situacao: true,
    },
    {
      descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elite.",
      situacao: false,
    },
    {
      descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elite.",
      situacao: false,
    },
    {
      descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elite.",
      situacao: true,
    },
  ],
  cursos: [
    {
      descricaoCurso: "FullCycle 2.0",
      data: "12/07/2021",
      mediaCurso: 30,
      mediaCursoPorcentagem: "30%",
      mediaCursoGeral: 30,
      mediaCursoGeralPorcentagem: "30%",
      mediaModuloGeral: 30,
      mediaModuloGeralPorcentagem: "30%",
      mediaCapitulosGeral: 30,
      mediaCapitulosGeralPorcentagem: "30%",
      modulos: [
        {
          descricao: "Docker",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
          capitulos: [
            {
              descricao: "Começando do zero",
              data: "12/07/2021",
              qtdAulas: "7 Aulas",
              valor: 30,
              porcentagem: "30%",
            },
            {
              descricao: "Começando do zero",
              data: "12/07/2021",
              qtdAulas: "7 Aulas",
              valor: 30,
              porcentagem: "30%",
            },
            {
              descricao: "Começando do zero",
              data: "12/07/2021",
              qtdAulas: "7 Aulas",
              valor: 30,
              porcentagem: "30%",
            },
            {
              descricao: "Começando do zero",
              data: "12/07/2021",
              qtdAulas: "7 Aulas",
              valor: 30,
              porcentagem: "30%",
            },
            {
              descricao: "Começando do zero",
              data: "12/07/2021",
              qtdAulas: "7 Aulas",
              valor: 30,
              porcentagem: "30%",
            },
            {
              descricao: "Começando do zero",
              data: "12/07/2021",
              qtdAulas: "7 Aulas",
              valor: 30,
              porcentagem: "30%",
            },
          ],
        },
        {
          descricao: "Padrões e Técnicas avançadas com Git e GitHub",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
        {
          descricao: "Integração contínua",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
        {
          descricao: "Docker",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
        {
          descricao: "Padrões e Técnicas avançadas com Git e GitHub",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
        {
          descricao: "Integração contínua",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
        {
          descricao: "Docker",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
        {
          descricao: "Padrões e Técnicas avançadas com Git e GitHub",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
        {
          descricao: "Integração contínua",
          data: "22/10/2021",
          porcentagem: "30%",
          valor: 30,
        },
      ],
    },
  ],
};
